name: Update feed
on:
  schedule:
    # This will run every ten minutes. Alter it using https://crontab.guru/.
    - cron: '*/10 * * * *'  
  workflow_dispatch:
jobs:
  bnn:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v7
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
      - name: Retrieve cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/mastofeedbot
          key: feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-
      - name: GitHub
        uses: 'joschi/mastofeedbot@v0.1.6'
        with:
          rss-feed: 'https://bnn.de/feed'
          # Visibility of the posted status (public | unlisted | private | direct)
          status-visibility: unlisted
          dry-run: false
          template: |
            {{{item.title}}}

            {{{item.link}}}

            {{{item.description}}}
          api-endpoint: "https://sueden.social"
          api-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          cache-file: ${{ github.workspace }}/mastofeedbot/cache.json
          cache-limit: 1000
